version: "3.8"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - '3333:3333'
    env_file:
      - ./back/.env
    depends_on:
      - mongo

  mongo:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: